### ISSUE TITLE
Incorrect error output

### ISSUE THREAD

**Issue by gkrasulya** [enb-make/enb-sass#1]
Hey!

Your enb technology is great. I'm currenty working on some project at Yandex and me and our team are happy that we can use sass with enb.

But there is a little problem with error output. Just today I got this:

19:44:12.632 - [failed] [app/pages/common/common.source.css] enb-sass
19:44:12.632 - [failed] [app/pages/common/_common.css] css-autoprefixer
19:44:12.632 - build failed
19:44:12.633 - build failed
undefined

I added console.log in technology file and then I saw:

{
  "status": 1,
  "file": "stdin",
  "line": 7729,
  "column": 17,
  "message": "unbound variable $popup-sidebar-add-info-height"
}

It will be great If you could add informative logging. Thanks!

**Comment by ixax** [comment]
Looks like bug: https://github.com/enb-make/enb-sass/blob/master/techs/css-sass.js#L56

**Comment by gkrasulya** [comment]
I think you should not `JSON.parse` catched error. It should be object already.

**Comment by ixax** [comment]
@blond looks like a `enb` bug, huh?

**Comment by DimitryDushkin** [comment]
It's a bug, that reproduces in io.js 2.5.0. In node 0.12.7 it's okay.

**Comment by DimitryDushkin** [comment]
I belive it can be closed now in favor of https://github.com/enb-make/enb-sass/pull/5
